name: New fpds search fields PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nanasess/setup-chromedriver@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.46.0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Scrape FPDS Site
        run: just scrape

      - name: Set Date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "minor: updating fields.json with newly identified ezSearch fields"
          title: 'minor: 🤖 [AUTOMATED] new ezSearch fields identified on {{ env.DATE }}'
          body: |
            Automated updates from FPDS ezSearch scraper.
            This PR is kept up to date automatically.
          branch: minor/new-ezsearch-fields
          base: master
          labels: automated, feature
          draft: false
